### ISSUE TITLE
RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.

### ISSUE THREAD

**Issue by huyingxi** [zixia/xi-lstm#1]
```
Traceback (most recent call last):
  File "src/main.py", line 464, in <module>
    print("current loss : ", loss.data)
  File "src/main.py", line 381, in run
    embedding_matrix = pickle.load(vocab)
  File "src/main.py", line 264, in __init__
    import ipdb;ipdb.set_trace()
RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.
```

**Comment by huan** [comment]
```
ipdb> l 278
    273         self.hidden_dim = hidden_dim
    274         self.word_embeddings = nn.Embedding(vocab_size, embedding_dim)
    275 
    276         ipdb.set_trace()
    277         npWeight = np.array(word_embed_weight)
--> 278         weight = torch.from_numpy(npWeight)
    279         self.word_embeddings.weight.data.copy_(weight)
    280 
    281         self.dropout = torch.nn.Dropout(0.5)
    282 
    283         self.lstmp = RNNModel(

ipdb> p type(word_embed_weight)
<class 'list'>
ipdb> p type(word_embed_weight[0])
<class 'numpy.ndarray'>
ipdb> p type(word_embed_weight[0][0])
<class 'numpy.float32'>
```
